# Generated by Django 5.2.13 on 2026-05-04 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('theme_colour', models.CharField(blank=True, help_text='Optional display colour, for example #1d4ed8', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='glossary.organisation')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SignEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('video_url', models.URLField(help_text='Use a verified video URL or clearly labelled placeholder during development.')),
                ('description', models.TextField()),
                ('usage_context', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated keywords for search support.', max_length=300)),
                ('is_quick_reference', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signs', to='glossary.category')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signs', to='glossary.organisation')),
            ],
            options={
                'verbose_name_plural': 'sign entries',
                'ordering': ['term'],
            },
        ),
        migrations.CreateModel(
            name='FAQEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='glossary.category')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='glossary.organisation')),
                ('related_sign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='glossary.signentry')),
            ],
            options={
                'verbose_name': 'FAQ entry',
                'verbose_name_plural': 'FAQ entries',
                'ordering': ['question'],
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('organisation', 'slug'), name='unique_category_slug_per_organisation'),
        ),
        migrations.AddConstraint(
            model_name='signentry',
            constraint=models.UniqueConstraint(fields=('organisation', 'slug'), name='unique_sign_slug_per_organisation'),
        ),
    ]
