# Generated by Django 5.2.13 on 2026-05-06 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0007_portalitem_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='signentry',
            name='is_official_published',
            field=models.BooleanField(default=True, help_text='Whether this sign has been reviewed and approved by interpreters.'),
        ),
        migrations.AddField(
            model_name='signentry',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='URL to a thumbnail image for the sign video'),
        ),
        migrations.AddField(
            model_name='signrequest',
            name='approval_notes',
            field=models.TextField(blank=True, help_text='Manager feedback on the sign request.'),
        ),
        migrations.AddField(
            model_name='signrequest',
            name='interpreter_notes',
            field=models.TextField(blank=True, help_text='Notes from interpreter/content review team.'),
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(help_text='Complete text transcription of the ISL sign for accessibility and search indexing.')),
                ('language', models.CharField(default='en', help_text="Language code (e.g., 'en' for English, 'ga' for Irish).", max_length=10)),
                ('sign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='glossary.signentry')),
            ],
            options={
                'ordering': ['sign__term'],
            },
        ),
    ]
