# Generated by Django 5.2.13 on 2026-05-14 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0008_signentry_is_official_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signentry',
            name='publication_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('needs_video', 'Needs video'), ('needs_review', 'Needs review'), ('published', 'Published'), ('archived', 'Archived')], default='published', help_text='Workflow status controlling whether this sign appears in public/staff glossary views.', max_length=30),
        ),
        migrations.AddField(
            model_name='signentry',
            name='video_review_status',
            field=models.CharField(choices=[('unchecked', 'Unchecked'), ('candidate_video', 'Candidate video'), ('approved_for_prototype', 'Approved for prototype'), ('broken_link', 'Broken link'), ('needs_replacement', 'Needs replacement')], default='unchecked', help_text='Simple review status for the linked sign video.', max_length=30),
        ),
        migrations.AddField(
            model_name='signrequest',
            name='decision_reason',
            field=models.TextField(blank=True, help_text='Reason for the manager or glossary manager decision.'),
        ),
        migrations.AddField(
            model_name='signrequest',
            name='request_type',
            field=models.CharField(choices=[('missing_sign', 'Missing sign'), ('incorrect_sign', 'Incorrect sign/video'), ('unclear_description', 'Unclear description'), ('wrong_category', 'Wrong category'), ('possible_duplicate', 'Possible duplicate'), ('broken_video_link', 'Broken video link'), ('other', 'Other')], default='missing_sign', max_length=30),
        ),
        migrations.AddField(
            model_name='signrequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_sign_requests', to='glossary.staffprofile'),
        ),
    ]
