# Generated by Django 5.2.13 on 2026-05-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0009_signentry_publication_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='role_type',
            field=models.CharField(choices=[('staff', 'Staff'), ('manager', 'Organisation manager'), ('glossary_manager', 'Glossary editor')], default='staff', max_length=30),
        ),
    ]
