# Generated by Django 5.2.13 on 2026-05-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0010_alter_staffprofile_role_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signrequest',
            name='decision_reason',
            field=models.TextField(blank=True, help_text='Reason for the organisation manager or glossary editor decision.'),
        ),
        migrations.AlterField(
            model_name='signrequest',
            name='interpreter_notes',
            field=models.TextField(blank=True, help_text='Notes from glossary editor or ISL/content review.'),
        ),
    ]
