# Generated by Django 5.2.11 on 2026-05-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0011_alter_signrequest_decision_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signentry',
            name='is_official_published',
            field=models.BooleanField(default=True, help_text='Whether this sign is approved for publication in this organisation glossary.'),
        ),
        migrations.AlterField(
            model_name='signrequest',
            name='interpreter_notes',
            field=models.TextField(blank=True, help_text='Notes from glossary editor or ISL/content review.', verbose_name='Glossary review notes'),
        ),
        migrations.AlterField(
            model_name='signrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending organisation-manager review'), ('needs_clarification', 'Needs clarification'), ('manager_approved', 'Ready for glossary review'), ('sent_to_interpreter', 'In glossary review'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=30),
        ),
    ]
