# Generated by Django 5.2.11 on 2026-05-14 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0012_alter_signentry_is_official_published_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignEntryChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('changed_fields', models.CharField(max_length=300)),
                ('change_summary', models.TextField()),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sign_change_logs', to='glossary.staffprofile')),
                ('sign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='glossary.signentry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
