# Generated by Django 5.2.11 on 2026-05-14 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0013_signentrychangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='signrequest',
            name='related_sign',
            field=models.ForeignKey(blank=True, help_text='Existing sign being reported, if this request is about a current glossary entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='glossary.signentry'),
        ),
    ]
